changing docker compose version, V1 to V2

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -85,19 +85,23 @@ jobs:
             MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
             EOF
 
-            # Deploy process
-            docker-compose pull
-            docker-compose up -d --force-recreate
+            # use 'docker compose' (with space) for version V2
+            docker compose pull
+            docker compose up -d --force-recreate
             docker image prune -f
 
-            # Health Check
+            # Health Check 
             echo "Waiting for backend to start..."
-            sleep 45
-            if curl -s http://localhost:8080/actuator/health | grep -q "status"; then
-              echo "Deployment Successful"
-              docker ps
-            else
-              echo "Deployment Failed - Printing backend logs:"
-              docker-compose logs --tail 100 gym-trainer-backend
-              exit 1
-            fi
+            for i in {1..10}; do
+              if curl -s http://localhost:8080/actuator/health | grep -q "UP"; then
+                echo "Deployment Successful"
+                docker ps
+                exit 0
+              fi
+              echo "Waiting... ($i/10)"
+              sleep 10
+            done
+
+            echo "Deployment Failed - Printing backend logs:"
+            docker compose logs --tail 100 gym-trainer-backend
+            exit 1
